apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      volumes:
      - name: code
        persistentVolumeClaim:
          claimName: code
      - name: config
        configMap:
          name: nginx-config
          items:
          - key: config
            path: site.conf
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        volumeMounts:
        - name: code
          mountPath: /code
        - name: config
          mountPath: /etc/nginx/conf.d

#      livenessProbe:
#        httpGet:
#          port: 8080
#          path: /
#        initialDelaySeconds: 10
#        periodSeconds: 5
#        timeoutSeconds: 2
#      readinessProbe:
#        httpGet:
#          port: 8080
#          path: /health
#        initialDelaySeconds: 10
#        periodSeconds: 5
  