---
apiVersion: v1
kind: Namespace
metadata:
  name: myapp

---
apiVersion: batch/v1
kind: Job
metadata:
  name: order-initdb-job
  namespace: myapp
spec:
  template:
    metadata:
      name: order-initdb-job
    spec:
      restartPolicy: Never
      initContainers:
      - name: check-db-ready
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        command:
          - sh
          - "-c"
          - |
            until mysqladmin ping -hmysql --silent;
            do echo waiting for database; sleep 2; done;
      containers:
      - name: post-install-job
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        image: mysql:5.6
        command: 
          - /bin/sh
          - "-c"
          - |
            mysql --host=mysql -uroot -ppassword myapp <<'EOF'
              create table b_order (id int NOT NULL AUTO_INCREMENT PRIMARY KEY, user_id int not null, price decimal(7,2) not null);
            EOF
  backoffLimit: 2
