---
apiVersion: v1
kind: Namespace
metadata:
  name: myapp

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: root-ingress
  namespace: myapp
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://app-auth-nginx-service.myapp.svc.cluster.local:8000/auth"
#    nginx.ingress.kubernetes.io/auth-signin: "http://$host/signin"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-User,X-Email,X-UserId,X-First-Name,X-Last-Name,X-Phone"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: arch.homework
    http:
      paths:
        - path: /users($|/)(.*)
          backend:
            serviceName: app-nginx-service
            servicePort: 8000
#        - path: /users/me
#- path: /otusapp/kirsanov($|/)(.*)
