openapi: 3.0.0
info:
  title: Оформление заказа
  version: 0.1.0
tags:
  - name: user
    description: Сервис работы с пользователем
  - name: order
    description: Сервис оформления заказа
paths:
  '/users/{userId}':
    get:
      tags:
        - user
      summary: Ресурс пользователя по ID
      description: Вернуть данные пользователя
      operationId: getUserById
      parameters:
        - name: userId
          in: path
          description: ID пользователя
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Неправильный запрос
        '404':
          description: Такого пользователя нет
  '/orders/{orderId}':
    get:
      tags:
        - order
      summary: Заказ по ID
      description: Вернуть данные заказа
      operationId: getOrderById
      parameters:
        - name: orderId
          in: path
          description: ID заказа
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Неправильный запрос
        '404':
          description: Такого заказа нет
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        phone:
          type: string
        address:
          type: string
      required: 
          - username
          - password
          - email
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
        userid:
          type: integer
          format: int64
        sum:
          type: integer
          format: int64
      required: 
          - userid
          - sum
