apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "myapp-chart.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    {{- range .Values.ingress.hosts }}
      - host: {{ .host | quote }}
        http:
          paths:
            - path: {{ .path | quote }}
              backend:
                serviceName: {{ .serviceName }}
                servicePort: {{ .servicePort }}
    {{- end }}
