---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-candidate-php-config
data:
  DB_HOST: mysqlc
  DB_NAME: myapp
  DB_USER: root

---
apiVersion: v1
kind: Secret
metadata:
  name: app-candidate-php-secret
type: Opaque
data:
  DB_PWD: cGFzc3dvcmQ=
