{
 "title": "PRS by endpoints",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "500",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}"
    }
   ]
  },
  {
   "title": "Nginx Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(nginx_ingress_controller_response_duration_seconds_bucket[2m])))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(nginx_ingress_controller_response_duration_seconds_bucket[2m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(nginx_ingress_controller_response_duration_seconds_bucket[2m])))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Nginx RPS by status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(nginx_ingress_controller_request_duration_seconds_count[2m]))",
     "legendFormat": "RPS {{status}}"
    }
   ]
  },
  {
   "title": "Nginx RPS by endpoint",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(nginx_ingress_controller_request_duration_seconds_count[2m]))",
     "legendFormat": "RPS {{endpoint}}"
    }
   ]
  },
  {
   "title": "Latency (nanoseconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(myapp_app_request_latency_nanoseconds_bucket[2m])))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(myapp_app_request_latency_nanoseconds_bucket[2m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(myapp_app_request_latency_nanoseconds_bucket[2m])))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "RPS by http_status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (http_status) (rate(myapp_app_request_count[2m]))",
     "legendFormat": "RPS {{http_status}}"
    }
   ]
  },
  {
   "title": "RPS by endpoints",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_endpoint) (rate(myapp_app_request_count[2m]))",
     "legendFormat": "RPS {{exported_endpoint}}"
    }
   ]
  }
 ]
}