---
apiVersion: v1
kind: Namespace
metadata:
  name: myapp

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: php-config
  namespace: myapp
data:
  DB_HOST: mysql
  DB_NAME: myapp
  DB_USER: root

---
apiVersion: v1
kind: Secret
metadata:
  name: php-secret
  namespace: myapp
type: Opaque
data:
  DB_PWD: cGFzc3dvcmQ=
